// Generated by `uv run python -m annex capture`. Do not edit.
//
// One captured answer per question and version, keyed the way
// `annex.eval.capture.fixture_filename` names the files. `src/lib/replay.ts`
// is the only module that reads this one.
import manifest from './manifest.json'
import q01SupportChatbotConsolidated from './q01-support-chatbot.consolidated.json'
import q01SupportChatbotOriginal from './q01-support-chatbot.original.json'
import q02SyntheticVoiceAgentConsolidated from './q02-synthetic-voice-agent.consolidated.json'
import q02SyntheticVoiceAgentOriginal from './q02-synthetic-voice-agent.original.json'
import q03GeneratedProductImagesConsolidated from './q03-generated-product-images.consolidated.json'
import q03GeneratedProductImagesOriginal from './q03-generated-product-images.original.json'
import q04CvScreeningConsolidated from './q04-cv-screening.consolidated.json'
import q04CvScreeningOriginal from './q04-cv-screening.original.json'
import q05UniversityAdmissionConsolidated from './q05-university-admission.consolidated.json'
import q05UniversityAdmissionOriginal from './q05-university-admission.original.json'
import q06WorkerPromotionConsolidated from './q06-worker-promotion.consolidated.json'
import q06WorkerPromotionOriginal from './q06-worker-promotion.original.json'
import q07RetrainedCreditModelConsolidated from './q07-retrained-credit-model.consolidated.json'
import q07RetrainedCreditModelOriginal from './q07-retrained-credit-model.original.json'
import q08RedesignedInterfaceConsolidated from './q08-redesigned-interface.consolidated.json'
import q08RedesignedInterfaceOriginal from './q08-redesigned-interface.original.json'
import q09WiderRolloutConsolidated from './q09-wider-rollout.consolidated.json'
import q09WiderRolloutOriginal from './q09-wider-rollout.original.json'
import q10HighRiskDeadlineConsolidated from './q10-high-risk-deadline.consolidated.json'
import q10HighRiskDeadlineOriginal from './q10-high-risk-deadline.original.json'
import q11ProhibitedDeadlineConsolidated from './q11-prohibited-deadline.consolidated.json'
import q11ProhibitedDeadlineOriginal from './q11-prohibited-deadline.original.json'
import q12GpaiDeadlineConsolidated from './q12-gpai-deadline.consolidated.json'
import q12GpaiDeadlineOriginal from './q12-gpai-deadline.original.json'

export { manifest }

export const captures: Record<string, unknown> = {
  'q01-support-chatbot.consolidated': q01SupportChatbotConsolidated,
  'q01-support-chatbot.original': q01SupportChatbotOriginal,
  'q02-synthetic-voice-agent.consolidated': q02SyntheticVoiceAgentConsolidated,
  'q02-synthetic-voice-agent.original': q02SyntheticVoiceAgentOriginal,
  'q03-generated-product-images.consolidated':
    q03GeneratedProductImagesConsolidated,
  'q03-generated-product-images.original': q03GeneratedProductImagesOriginal,
  'q04-cv-screening.consolidated': q04CvScreeningConsolidated,
  'q04-cv-screening.original': q04CvScreeningOriginal,
  'q05-university-admission.consolidated': q05UniversityAdmissionConsolidated,
  'q05-university-admission.original': q05UniversityAdmissionOriginal,
  'q06-worker-promotion.consolidated': q06WorkerPromotionConsolidated,
  'q06-worker-promotion.original': q06WorkerPromotionOriginal,
  'q07-retrained-credit-model.consolidated':
    q07RetrainedCreditModelConsolidated,
  'q07-retrained-credit-model.original': q07RetrainedCreditModelOriginal,
  'q08-redesigned-interface.consolidated': q08RedesignedInterfaceConsolidated,
  'q08-redesigned-interface.original': q08RedesignedInterfaceOriginal,
  'q09-wider-rollout.consolidated': q09WiderRolloutConsolidated,
  'q09-wider-rollout.original': q09WiderRolloutOriginal,
  'q10-high-risk-deadline.consolidated': q10HighRiskDeadlineConsolidated,
  'q10-high-risk-deadline.original': q10HighRiskDeadlineOriginal,
  'q11-prohibited-deadline.consolidated': q11ProhibitedDeadlineConsolidated,
  'q11-prohibited-deadline.original': q11ProhibitedDeadlineOriginal,
  'q12-gpai-deadline.consolidated': q12GpaiDeadlineConsolidated,
  'q12-gpai-deadline.original': q12GpaiDeadlineOriginal,
}
